src/controllers/DefaultController.php
<?php

namespace goenergies\yii2\audit\controllers;

use goenergies\yii2\audit\components\panels\RendersSummaryChartTrait;
use goenergies\yii2\audit\components\web\Controller;
use goenergies\yii2\audit\models\AuditEntry;
use Yii;

/**
 * DefaultController
 * @package goenergies\yii2\audit\controllers
 */
class DefaultController extends Controller
{
    use RendersSummaryChartTrait;

    /**
     * Module Default Action.
     * @return mixed
     */
    public function actionIndex()
    {
        $chartData = $this->getChartData();
        return $this->render('index', ['chartData' => $chartData]);
    }

    protected function getChartModel()
    {
        return AuditEntry::className();
    }
}

src/controllers/EntryController.php
<?php

namespace goenergies\yii2\audit\controllers;

use goenergies\yii2\audit\components\panels\Panel;
use goenergies\yii2\audit\components\web\Controller;
use goenergies\yii2\audit\models\AuditEntry;
use goenergies\yii2\audit\models\AuditEntrySearch;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;

/**
 * EntryController
 * @package goenergies\yii2\audit\controllers
 */
class EntryController extends Controller
{
    /**
     * @var array fake summary data so the debug panels work
     */
    public $summary = ['tag' => ''];

    /**
     * Lists all AuditEntry models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AuditEntrySearch;
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel'  => $searchModel,
        ]);
    }

    /**
     * Displays a single AuditEntry model.
     * @param integer $id
     * @param string  $panel
     * @return mixed
     * @throws \yii\base\InvalidConfigException
     */
    public function actionView($id, $panel = '')
    {
        list($model, $panels) = $this->loadData($id);
        if (isset($panels[$panel]))
            $activePanel = $panel;
        else {
            reset($panels);
            $activePanel = key($panels);
        }

        $this->summary['tag'] = $id;
        // @TODO: Add unknown panels as "generic data"

        return $this->render('view', [
            'id'          => $id,
            'model'       => $model,
            'activePanel' => $activePanel ? $panels[$activePanel] : null,
            'panels'      => $panels,
        ]);
    }

    /**
     * @return array
     */
    public function actions()
    {
        $actions = [];
        foreach ($this->module->panels as $panel) {
            $actions = array_merge($actions, $panel->actions);
        }
        return $actions;
    }

    /**
     * @param $id
     * @return AuditEntry|Panel[]
     * @throws NotFoundHttpException
     */
    public function loadData($id)
    {
        /** @var AuditEntry $model */
        $model = AuditEntry::findOne($id);
        if (!$model) {
            throw new NotFoundHttpException('The requested entry does not exist.');
        }

        // Why the separate panel list here?
        // Because we don't want to interfere with the modules' regular configuration.
        // We might as well be viewing an entry that has data for more panels than those who are currently active.
        // Updating the actual module panels would mean that for all audit viewing that panel would become active again

        $panels = $this->module->loadPanels($this->module->getPanelIdentifiers());
        $activePanels = [];
        $data = ArrayHelper::getColumn($model->data, 'data');
        foreach ($panels as $panelId => $panel)
            if ($panel->hasEntryData($model)) {
                $panel->tag = $id;
                $panel->model = $model;
                $panel->load(isset($data[$panelId]) ? $data[$panelId] : null);
                $activePanels[$panelId] = $panel;
            }

        return [$model, $activePanels];
    }
}

src/views/entry/index.php
<?php

use goenergies\yii2\audit\Audit;
use yii\helpers\Html;
use yii\grid\GridView;

use goenergies\yii2\audit\models\AuditEntrySearch;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('audit', 'Entries');
$this->params['breadcrumbs'][] = ['label' => Yii::t('audit', 'Audit'), 'url' => ['default/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="audit-entry-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\ActionColumn', 'template' => '{view}'],
            'id',
            [
                'attribute' => 'user_id',
                'label' => Yii::t('audit', 'User'),
                'class' => 'yii\grid\DataColumn',
                'value' => function ($data) {
                    return Audit::getInstance()->getUserIdentifier($data->user_id);
                },
                'format' => 'raw',
            ],
            'ip',
            [
                'filter' => AuditEntrySearch::methodFilter(),
                'attribute' => 'request_method',
            ],
            [
                'filter' => [1 => \Yii::t('audit', 'Yes'), 0 => \Yii::t('audit', 'No')],
                'attribute' => 'ajax',
                'value' => function($data) {
                    return $data->ajax ? Yii::t('audit', 'Yes') : Yii::t('audit', 'No');
                },
            ],
            [
                'class' => 'yii\grid\DataColumn',
                'attribute' => 'route',
                'filter' => AuditEntrySearch::routeFilter(),
                'format' => 'html',
                'value' => function ($data) {
                    return HTML::tag('span', '', [
                        'title' => \yii\helpers\Url::to([$data->route]),
                        'class' => 'glyphicon glyphicon-link'
                    ]) . ' ' . $data->route;
                },
            ],
            [
                'attribute' => 'duration',
                'format' => 'decimal',
                'contentOptions' => ['class' => 'text-right', 'width' => '100px'],
            ],
            [
                'attribute' => 'memory_max',
                'format' => 'shortsize',
                'contentOptions' => ['class' => 'text-right', 'width' => '100px'],
            ],
            [
                'attribute' => 'trails',
                'value' => function ($data) {
                    return $data->trails ? count($data->trails) : '';
                },
                'contentOptions' => ['class' => 'text-right'],
            ],
            [
                'attribute' => 'mails',
                'value' => function ($data) {
                    return $data->mails ? count($data->mails) : '';
                },
                'contentOptions' => ['class' => 'text-right'],
            ],
            [
                'attribute' => 'javascripts',
                'value' => function ($data) {
                    return $data->javascripts ? count($data->javascripts) : '';
                },
                'contentOptions' => ['class' => 'text-right'],
            ],
            [
                'attribute' => 'errors',
                'value' => function ($data) {
                    return $data->linkedErrors ? count($data->linkedErrors) : '';
                },
                'contentOptions' => ['class' => 'text-right'],
            ],
            [
                'attribute' => 'created',
                'options' => ['width' => '150px'],
            ],
        ],
    ]); ?>
</div>

src/views/entry/view.php
<?php

/** @var View $this */
/** @var Panel[] $panels */
/** @var Panel $activePanel */
/** @var AuditEntry $model */

use goenergies\yii2\audit\Audit;
use goenergies\yii2\audit\components\panels\Panel;
use goenergies\yii2\audit\models\AuditEntry;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

foreach ($panels as $panel) {
    $panel->registerAssets($this);
}

$this->title = Yii::t('audit', 'Entry #{id}', ['id' => $model->id]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('audit', 'Audit'), 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('audit', 'Entries'), 'url' => ['index']];
$this->params['breadcrumbs'][] = '#' . $model->id;

?>

<?= Html::tag('h1', $this->title) ?>

    <div class="row">
        <div class="col-md-6">
            <?php
            echo Html::tag('h2', Yii::t('audit', 'Request'), ['id' => 'entry', 'class' => 'hashtag']);

            if ($model->request_method == 'CLI') {
                $attributes = [
                    'route',
                    'request_method',
                ];
            } else {
                $attributes = [
                    [
                        'label' => $model->getAttributeLabel('user_id'),
                        'value' => Audit::getInstance()->getUserIdentifier($model->user_id),
                        'format' => 'raw',
                    ],
                    'ip',
                    'route',
                    'request_method',
                    [
                        'label' => $model->getAttributeLabel('ajax'),
                        'value' => $model->ajax ? Yii::t('audit', 'Yes') : Yii::t('audit', 'No'),
                    ],
                    [
                        'label' => Yii::t('audit', 'Request URL'),
                        'value' => $model->getRequestUrl(),
                    ],
                ];
            }

            echo DetailView::widget([
                'model' => $model,
                'attributes' => $attributes
            ]);
            ?>
        </div>
        <div class="col-md-6">
            <?php
            echo Html::tag('h2', Yii::t('audit', 'Profiling'), ['id' => 'entry', 'class' => 'hashtag']);

            $attributes = [
                ['attribute' => 'duration', 'format' => 'decimal'],
                ['attribute' => 'memory_max', 'format' => 'shortsize'],
                'created',
            ];

            echo DetailView::widget([
                'model' => $model,
                'attributes' => $attributes
            ]);
            ?>
        </div>
    </div>

<?php Pjax::begin(['id' => 'audit-panels', 'timeout' => 0]); ?>
    <div class="row">
        <div class="col-md-2">
            <div class="list-group">
                <?php
                foreach ($panels as $id => $panel) {
                    $label = '<i class="glyphicon glyphicon-chevron-right"></i>' . $panel->getLabel();
                    echo Html::a($label, ['view', 'id' => $model->id, 'panel' => $id], [
                        'class' => $panel === $activePanel ? 'list-group-item active' : 'list-group-item',
                    ]);
                }
                ?>
            </div>
        </div>
        <div class="col-md-10">
            <?php if ($activePanel) { ?>
                <?= $activePanel->getDetail(); ?>
                <input type="hidden" name="panel" value="<?= $activePanel->id ?>"/>
            <?php } ?>
        </div>
    </div>
<?php Pjax::end(); ?>